### ISSUE TITLE
Include baterry specs in  list of items needed

### ISSUE THREAD

**Issue by Octavio-1** [karnold/cellular_gps_tracker#1]
please what is the specs of the baterry used?..thanks in advance.sorry for bump

**Comment by karnold** [comment]
any standard dc battery will work that provides 6volts or more. you will have the most success with a 12v battery that is rated at least 4000mah

—
Kristen

**Comment by Octavio-1** [comment]
should i connect baterry terminal to arduino's Vin and  Gnd pins or through power jack?

**Comment by karnold** [comment]
http://playground.arduino.cc/Learning/9VBatteryAdapter
